//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::color::Entity as Color;
pub use super::file_has_tags::Entity as FileHasTags;
pub use super::file_system_identifier::Entity as FileSystemIdentifier;
pub use super::file_types::Entity as FileTypes;
pub use super::files::Entity as Files;
pub use super::folders::Entity as Folders;
pub use super::icon::Entity as Icon;
pub use super::tag_has_tags::Entity as TagHasTags;
pub use super::tags::Entity as Tags;
pub use super::thumbnails::Entity as Thumbnails;
