//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "folders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub content_hash: String,
    pub identity_hash: String,
    pub structure_hash: String,
    pub file_system_id: i32,
    pub parent_folder_id: Option<i32>,
    pub name: String,
    pub path: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::file_system_identifier::Entity",
        from = "Column::ParentFolderId",
        to = "super::file_system_identifier::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FileSystemIdentifier2,
    #[sea_orm(
        belongs_to = "super::file_system_identifier::Entity",
        from = "Column::FileSystemId",
        to = "super::file_system_identifier::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FileSystemIdentifier1,
}

impl ActiveModelBehavior for ActiveModel {}
