//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod color;
pub mod file_has_tags;
pub mod file_system_identifier;
pub mod file_types;
pub mod files;
pub mod folders;
pub mod icon;
pub mod tag_has_tags;
pub mod tags;
pub mod thumbnails;
