//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::file_has_tags::Entity as FileHasTags;
pub use super::file_types::Entity as FileTypes;
pub use super::files::Entity as Files;
pub use super::tag_has_tags::Entity as TagHasTags;
pub use super::tags::Entity as Tags;
