//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tag_has_tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub super_tag_id: i32,
    pub sub_tag_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tags::Entity",
        from = "Column::SuperTagId",
        to = "super::tags::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tags2,
    #[sea_orm(
        belongs_to = "super::tags::Entity",
        from = "Column::SubTagId",
        to = "super::tags::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tags1,
}

impl ActiveModelBehavior for ActiveModel {}
