//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::file_has_tags::Entity")]
    FileHasTags,
}

impl Related<super::file_has_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileHasTags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
