#---cargo---
name: rust

on:
  push:
    branches: [ "main", "dev", "test", "cicd" ]
  pull_request:
    branches: ["main", "dev", "test"]

jobs: #can run in parallel when creating seperate jobs
  cargo-build:
    name: cargo-build-and-test
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    # runs-on: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Install system dependencies for ubuntu # tauri v2 https://tauri.app/start/prerequisites/
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: cargo-version
        run: |
          echo "cargo version in use: $(cargo --version)"

      - name: cargo-check
        run: cargo check --manifest-path=./app/Cargo.toml --verbose

      - name: cargo-build
        if: always()
        run: cargo build --manifest-path=./app/Cargo.toml --verbose

      - name: cargo-test
        if: always()
        run: cargo test --manifest-path=./app/Cargo.toml --verbose

  deno-build:
    name: deno-build-and-test
    runs-on: ubuntu-latest
    # runs-on: [ ubuntu-latest, windows-latest, macos-latest ]
    permissions:
      contents: read #---deno---

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # - name: Setup tauri-cli
      #   run: |
      #     cargo install tauri-cli
      
      - name: Initilize deno dev environment
        run: |
          cd ./app
          deno install

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        if: always()
        run: deno lint

      - name: Run tests
        if: always()
        run: |
          cd ./app
          deno task tauri dev
          # deno test tauri dev
